### ISSUE TITLE
terraform-provider-vra_v0.3.9 plugin crashed panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lirany1** [vmware/terraform-provider-vra#432]
### Code of Conduct

This project has a Code of Conduct that all participants are expected to understand and follow:
* [ ] I have read and agree to the project's [Code of Conduct](https://github.com/vmware/terraform-provider-vra/blob/main/CODE-OF-CONDUCT.md)

### vRA Version

VRA8

### Terraform Version

latest

### Terraform Configuration Files

```
 container('terraform') {
                            sh "terraform -chdir=${TERRAFORM_VRA_SINGLE_CLUSTER_PATH} destroy -auto-approve"
                        }```
```
hcl
# Copy-paste your Terraform configurations here.
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.

### Panic Output

```00:00:54  vra_deployment.this: Still destroying... [id=196c511e-9a60-453a-a98c-e4aa0f799ea2, 1m10s elapsed]
00:01:04  vra_deployment.this: Still destroying... [id=196c511e-9a60-453a-a98c-e4aa0f799ea2, 1m20s elapsed]
00:01:08  ╷
00:01:08  │ Error: Plugin did not respond
00:01:08  │ 
00:01:08  │ The plugin encountered an error, and failed to respond to the
00:01:08  │ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
00:01:08  │ contain more details.
00:01:08  ╵
00:01:08  
00:01:08  Stack trace from the terraform-provider-vra_v0.3.9 plugin:
00:01:08  
00:01:08  panic: runtime error: invalid memory address or nil pointer dereference
00:01:08  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10ebb6d]
00:01:08  
00:01:08  goroutine 119 [running]:
00:01:08  github.com/vmware/vra-sdk-go/pkg/client/deployments.(*GetDeploymentByIDUsingGETOK).Error(...)
00:01:08  	github.com/vmware/vra-sdk-go@v0.2.21/pkg/client/deployments/get_deployment_by_id_using_get_responses.go:63
00:01:08  github.com/vmware/terraform-provider-vra/vra.deploymentDeleteStatusRefreshFunc.func1(0xc0009bbf00, 0xc0009bbec8, 0x0, 0x0, 0x2, 0x1)
00:01:08  	github.com/vmware/terraform-provider-vra/vra/resource_deployment.go:1113 +0x22d
00:01:08  github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState.func1(0xc000842480, 0xc0007869a0, 0xc0004edcc0, 0xc0000457a0, 0xc000afd930, 0xc000afd928)
00:01:08  	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/resource/state.go:103 +0x27a
00:01:08  created by github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState
00:01:08  	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/resource/state.go:80 +0x1c5
00:01:08  
00:01:08  Error: The terraform-provider-vra_v0.3.9 plugin crashed!
00:01:08  
00:01:08  This is always indicative of a bug within the plugin. It would be immensely
00:01:08  helpful if you could report the crash with the plugin's maintainers so that it
00:01:08  can be fixed. The output above should help diagnose the issue.
```
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
If this issue is reproducible with the [latest](https://github.com/vmware/terraform-provider-vra/releases/latest) (_0.6.0 as of this date; 0.3.9 reported_) version of the provider, please comment.  Otherwise, I'd recommend closing this stale issue.

cc @frodenas
