### ISSUE TITLE
x509: certificate signed by unknown authority when terraform plan

### ISSUE THREAD

**Issue by moffzilla** [vmware/terraform-provider-vra#72]
When trying to apply a plan to a vRA8 endpoint ( vRA 8 On-Prem)
I get the error 
==============
Error: Post https://cava-n-89-120.eng.vmware.com/iaas/api/login: x509: certificate signed by unknown authority

  on main.tf line 1, in provider "vra":
   1: provider "vra" {
==============

Tried introducing  variable : ignore_cert_warning = "true"
but it doesn't seem to be supported....

==============
Error: Unsupported argument

  on main.tf line 4, in provider "vra":
   4:   ignore_cert_warning = "true"
==============

Any workaround?

**Comment by dmettem** [comment]
@moffzilla Please try with the `insecure` argument.

**Comment by moffzilla** [comment]
Thank you "insecure = true" seems to help
Although now it complains about the data_collector, which it is not available as this is a vRA8 On-Prem and there is not Cloud Proxy... 

data.vra_data_collector.dc: Refreshing state...

Error: unknown error (status 404): {resp:0xc0005545a0}

  on main.tf line 7, in data "vra_data_collector" "dc":
   7: data "vra_data_collector" "dc" {

=========

is there a way to by pass the data collector?

**Comment by markpeek** [comment]
You may need to try changing this [line](https://github.com/vmware/terraform-provider-vra/blob/master/vra/resource_cloud_account_vsphere.go#L27) to `Required: false,` and then remove the vra_data_collector from your template.

**Comment by moffzilla** [comment]
Ok I did the change as suggested:
//////////////////////////////////                       
"dcid": &schema.Schema{
                                Type:     schema.TypeString,
                                Required: false,

Also from my terraform.tfvars
then from my main.tf 

//////////////////////////////////
provider "vra" {
  url           = var.url
  refresh_token = var.refresh_token
  insecure = "true"
}

data "vra_region_enumeration" "dc_regions" {
  username = var.username
  password = var.password
  hostname = var.hostname
}

resource "vra_cloud_account_vsphere" "this" {
  name        = "tf-vsphere-account"
  description = "foobar"
  username    = var.username
  password    = var.password
  hostname    = var.hostname

  regions                 = data.vra_region_enumeration.dc_regions.regions
  accept_self_signed_cert = true

  tags {
    key   = "foo"
    value = "bar"
  }
}
//////////////////////////////////

I "terraform init", with "-plugin-dir" to make sure I include the new provider plug-in
but when I run "terraform plan", I am prompted for the datacollector, his is what I get:

/////////////////

var.datacollector
  Enter a value: test

Error: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
	* resource vra_cloud_account_vsphere: dcid: One of optional, required, or computed must be set
 /////////////////

Even if I remove "var.datacollector" from "variables.tf" I get the same error without being prompted for dc

**Comment by markpeek** [comment]
I likely responded with the wrong suggestion. Try replacing the `Required` line with `Optional: true,`.

**Comment by mdittbrenner215** [comment]
provider "vra" {
  url           = var.url
  refresh_token = var.refresh_token
  insecure = "true"
}

I have been using this with no issues

**Comment by dmettem** [comment]
Will make dcid optional to support both vRA 8.0 and vRA Cloud.

**Comment by dmettem** [comment]
dcid is now made optional with PR https://github.com/vmware/terraform-provider-vra/pull/82.

@moffzilla Please pull and use the latest bits. Let me know if I can close this issue now.

**Comment by moffzilla** [comment]
I downloaded the v0.1.0 vRA provider binary
Performed couple of test with a vRA on Prem Version 8.0.0.6619 (14842736)

1) I configure my variables, I remove  datacollector = "" hen Initialization went Ok but if I try a plan, I get an unknown error below.... got the feeling I must missing some configuration, besides removing the datacollector, what else is needed?
I attach the crash.log
[crash.log](https://github.com/vmware/terraform-provider-vra/files/3780631/crash.log)

////////////////////
root@ubuntu_server:/tempo/examples/cloud_account_vsphere# terraform plan
var.datacollector
  Enter a value:

var.datacollector
  Enter a value: testa

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.vra_data_collector.dc[0]: Refreshing state...

Error: unknown error (status 404): {resp:0xc000420b40}

  on main.tf line 8, in data "vra_data_collector" "dc":
   8: data "vra_data_collector" "dc" {

root@ubuntu_server:/tempo/examples/cloud_account_vsphere#

////////////////////

2)  I configure my variables, left in datacollector = "" but empty then Initialization went Ok but if I try a plan, I get a "panic error"

///////////////////////
root@ubuntu_server:/tempo/examples/cloud_account_vsphere# terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.vra_region_enumeration.dc_regions: Refreshing state...

Error: rpc error: code = Canceled desc = context canceled

panic: runtime error: invalid memory address or nil pointer dereference
2019-10-28T20:23:09.988Z [DEBUG] plugin.terraform-provider-vra: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x100e134]
2019-10-28T20:23:09.988Z [DEBUG] plugin.terraform-provider-vra:
2019-10-28T20:23:09.988Z [DEBUG] plugin.terraform-provider-vra: goroutine 64 [running]:
2019-10-28T20:23:09.988Z [DEBUG] plugin.terraform-provider-vra: github.com/vmware/terraform-provider-vra/vra.dataSourceRegionEnumerationRead(0xc000102ee0, 0x10e4b20, 0xc00000cde0, 0xc000102ee0, 0x0)
2019-10-28T20:23:09.988Z [DEBUG] plugin.terraform-provider-vra: 	/Users/mark/github/vmware/terraform-provider-vra/vra/data_source_region_enumeration.go:54 +0x2f4
2019-10-28T20:23:09.988Z [DEBUG] plugin.terraform-provider-vra: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0xc0004c2000, 0xc000420640, 0x10e4b20, 0xc00000cde0, 0xc0006refresh_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ijk4Nzg4OTE5MTIwMTY3NTkyNjUifQ.eyJpc3MiOiJDTj1QcmVsdWRlIElkZW50aXR5IFNlcnZpY2UsT1U9Q01CVSxPPVZNd2FyZSxMPVNvZmlhLFNUPVNvZmlhLEM9QkciLCJpYXQiOjE1Nz83ac8, 0x1, 0x0)
2019-10-28T20:23:09.988Z [DEBUG] plugin.terraform-provider-vra: 	/Users/mark/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/resource.go:398 +0x88
2019-10-28T20:23:09.988Z [DEBUG] plugin.terraform-provider-vra: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0xc0003e1400, 0xc00081bb28, 0xc000420640, 0xc000420640, 0x0, 0x0)
2019-10-28T20:23:09.988Z [DEBUG] plugin.terraform-provider-vra: 	/Users/mark/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/provider.go:451 +0x17f
2019-10-28T20:23:09.988Z [DEBUG] plugin.terraform-provider-vra: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc00000e270, 0x1635460, 0xc0004054d0, 0xc0004cb1c0, 0xc00000e270, 0xc0004054d0, 0xc0001d4bd0)
2019-10-28T20:23:09.988Z [DEBUG] plugin.terraform-provider-vra: 	/Users/mark/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:1036 +0x44f
2019-10-28T20:23:09.989Z [DEBUG] plugin.terraform-provider-vra: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadDataSource_Handler(0x133bb00, 0xc00000e270, 0x1635460, 0xc0004054d0, 0xc000608a20, 0x0, 0x1635460, 0xc0004054d0, 0xc0005406c0, 0x8a)
2019-10-28T20:23:09.989Z [DEBUG] plugin.terraform-provider-vra: 	/Users/mark/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3225 +0x23e
2019-10-28T20:23:09.989Z [DEBUG] plugin.terraform-provider-vra: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00053a160, 0x1643000, 0xc000461800, 0xc00060fc00, 0xc000515ec0, 0x20a8d90, 0x0, 0x0, 0x0)
2019-10-28T20:23:09.989Z [DEBUG] plugin.terraform-provider-vra: 	/Users/mark/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:995 +0x466
2019-10-28T20:23:09.989Z [DEBUG] plugin.terraform-provider-vra: google.golang.org/grpc.(*Server).handleStream(0xc00053a160, 0x1643000, 0xc000461800, 0xc00060fc00, 0x0)
2019-10-28T20:23:09.989Z [DEBUG] plugin.terraform-provider-vra: 	/Users/mark/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1275 +0xda6
2019-10-28T20:23:09.989Z [DEBUG] plugin.terraform-provider-vra: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000518170, 0xc00053a160, 0x1643000, 0xc000461800, 0xc00060fc00)
2019-10-28T20:23:09.989Z [DEBUG] plugin.terraform-provider-vra: 	/Users/mark/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:710 +0x9f
2019-10-28T20:23:09.989Z [DEBUG] plugin.terraform-provider-vra: created by google.golang.org/grpc.(*Server).serveStreams.func1
2019-10-28T20:23:09.989Z [DEBUG] plugin.terraform-provider-vra: 	/Users/mark/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:708 +0xa1
2019-10-28T20:23:09.990Z [DEBUG] plugin: plugin process exited: path=/tempo/terraform-provider-vra pid=4306 error="exit status 2"
2019/10/28 20:23:09 [ERROR] <root>: eval: *terraform.EvalReadData, err: rpc error: code = Canceled desc = context canceled
2019/10/28 20:23:09 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Canceled desc = context canceled
2019/10/28 20:23:09 [TRACE] [walkRefresh] Exiting eval tree: data.vra_region_enumeration.dc_regions
2019/10/28 20:23:09 [TRACE] vertex "data.vra_region_enumeration.dc_regions": visit complete
2019/10/28 20:23:09 [TRACE] vertex "data.vra_region_enumeration.dc_regions": dynamic subgraph encountered errors
2019/10/28 20:23:09 [TRACE] vertex "data.vra_region_enumeration.dc_regions": visit complete
2019/10/28 20:23:09 [TRACE] dag/walk: upstream of "provider.vra (close)" errored, so skipping
2019/10/28 20:23:09 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2019/10/28 20:23:09 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2019-10-28T20:23:09.991Z [DEBUG] plugin: plugin exited
url = "https://cava-n-89-120.eng.vmware.com"


refresh_token = "dOrDo0dlgBHtF5zDx4FIhkO1Ve7nmV1Q"

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
///////////////////////

**Comment by dmettem** [comment]
@moffzilla Can this be closed? There are several new versions released since then, so you may need to try with newer binary. Thanks!

**Comment by moffzilla** [comment]
Yes let's close it I was able to validate the option

**Comment by dmettem** [comment]
Thanks @moffzilla!
